build-fedora:
  image: fedora:latest
  before_script:
    - dnf install -y meson libxml2-devel vala gettext itstool gtk3-devel geocode-glib-devel gobject-introspection-devel libsoup-devel
  script:
    - meson _build
    - ninja -C _build test
    - ninja -C _build install
